# Generated by Django 3.0.3 on 2020-02-15 13:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('demo', 'Demo'), ('retired', 'Retired')], max_length=10)),
                ('trackingDays', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('active', 'Active'), ('demo', 'Demo'), ('retired', 'Retired')], max_length=10)),
                ('setupDate', models.DateField()),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Client')),
                ('defaultScenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Scenario')),
            ],
        ),
    ]
