# Generated by Django 3.0.3 on 2020-02-15 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_userscenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('scenarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='BucketWeight',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('bucketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Bucket')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.User')),
            ],
        ),
    ]
