# Generated by Django 3.0.3 on 2020-02-17 07:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_bucketmodel_modeldetails_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lei', models.CharField(max_length=100)),
                ('dbpediaResource', models.CharField(max_length=100)),
                ('wikiResource', models.CharField(max_length=100)),
                ('historyProcessed', models.BooleanField(default=False)),
                ('entityType', models.CharField(max_length=100)),
                ('manualEntry', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeSource',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('scrapeInterval', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ModelDetails',
            new_name='ModelDetail',
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('unique_hash', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('search_keyword', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('body', models.CharField(max_length=10000)),
                ('status_code', models.IntegerField()),
                ('internal_source', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('entry_created', models.DateTimeField()),
                ('language', models.CharField(max_length=100)),
                ('source_country', models.CharField(max_length=100)),
                ('raw_file_source', models.CharField(max_length=100)),
                ('entityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Entity')),
                ('scenarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Scenario')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.User')),
            ],
        ),
        migrations.CreateModel(
            name='LastScraped',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lastScraped', models.DateTimeField()),
                ('entityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Entity')),
                ('scrapeSourceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.ScrapeSource')),
            ],
        ),
        migrations.CreateModel(
            name='EntityScore',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storyID', models.CharField(max_length=1000)),
                ('grossScore', models.FloatField()),
                ('bucketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Bucket')),
                ('entityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Entity')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.ModelDetail')),
                ('sourceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Source')),
            ],
        ),
        migrations.CreateModel(
            name='BucketScore',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storyID', models.CharField(max_length=100)),
                ('storyDate', models.DateTimeField()),
                ('grossScore', models.FloatField()),
                ('bucketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Bucket')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.ModelDetail')),
                ('sourceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('entityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Entity')),
            ],
        ),
    ]
