# Generated by Django 3.0.3 on 2020-02-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20200217_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='dbpediaResource',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='lei',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='wikiResource',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
