# Generated by Django 3.0.3 on 2020-02-23 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_auto_20200223_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='body',
        ),
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
        migrations.RemoveField(
            model_name='story',
            name='status_code',
        ),
        migrations.CreateModel(
            name='StoryBody',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(blank=True, max_length=10000, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('entryTime', models.DateField()),
                ('storyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Story')),
            ],
            options={
                'verbose_name_plural': 'bodies',
            },
        ),
    ]
