# Generated by Django 3.0.3 on 2020-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_auto_20200223_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storybody',
            name='entryTime',
            field=models.DateTimeField(),
        ),
    ]
