# Generated by Django 3.0.3 on 2020-02-23 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_auto_20200223_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storybody',
            options={'verbose_name_plural': 'story bodies'},
        ),
        migrations.AlterModelOptions(
            name='storyentities',
            options={'verbose_name_plural': 'story entities'},
        ),
        migrations.AlterModelOptions(
            name='storysentiment',
            options={'verbose_name_plural': 'story sentiment'},
        ),
        migrations.RenameField(
            model_name='bucketscore',
            old_name='storyDate',
            new_name='entryTime',
        ),
        migrations.AddField(
            model_name='entityscore',
            name='entryTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 29, 41, 842589)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storyentities',
            name='entryTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 30, 0, 84408)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storysentiment',
            name='entryTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 30, 11, 702596)),
            preserve_default=False,
        ),
    ]
