# Generated by Django 3.0.3 on 2020-02-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_auto_20200223_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='modeldetail',
            name='storage_link',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
