# Generated by Django 3.0.3 on 2020-02-25 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_modeldetail_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketscore',
            name='storyDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
