# Generated by Django 3.0.3 on 2020-02-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0025_bucketscore_storydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketscore',
            name='grossScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entityscore',
            name='grossScore',
            field=models.IntegerField(),
        ),
    ]
