# Generated by Django 3.0.3 on 2020-02-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0026_auto_20200225_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DashUser',
        ),
    ]
