# Generated by Django 3.0.3 on 2020-05-11 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0061_remove_storyentityref_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('wikipedia', models.CharField(blank=True, max_length=200)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.StoryEntityRef')),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.EntityType')),
            ],
            options={
                'verbose_name_plural': 'Alias',
            },
        ),
    ]
