# Generated by Django 3.0.3 on 2020-05-22 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0064_auto_20200522_1310'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='last_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.DashUser'),
        ),
    ]
