# Generated by Django 3.0.3 on 2020-06-19 07:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0066_userscenario_access'),
        ('entity', '0002_auto_20200522_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('wikipedia', models.CharField(blank=True, max_length=200)),
                ('render', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salience', models.FloatField(null=True)),
                ('mentions', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('storyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Story')),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.EntityType')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.DashUser')),
            ],
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('wikipedia', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salience', models.FloatField(null=True)),
                ('mentions', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('scenarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Scenario')),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.EntityType')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.DashUser')),
            ],
        ),
    ]
