# Generated by Django 3.0.3 on 2020-06-19 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_custom_dump'),
    ]

    operations = [
        migrations.AddField(
            model_name='dump',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
