# Generated by Django 3.0.3 on 2020-02-15 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_scenario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScenario',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Scenario')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.User')),
            ],
        ),
    ]
