# Generated by Django 3.0.3 on 2020-02-21 08:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_entity_scenarioid'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='body_analytics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='story',
            name='title_analytics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bucketscore',
            name='storyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Story'),
        ),
        migrations.AlterField(
            model_name='entityscore',
            name='storyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='entry_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='story',
            name='status_code',
            field=models.IntegerField(blank=True),
        ),
    ]
