# Generated by Django 3.0.3 on 2020-02-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20200221_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'verbose_name_plural': 'alias'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='lastscrape',
            options={'verbose_name_plural': 'last scrapes'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'portfolios'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='domain',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='story',
            name='raw_file_source',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='search_keyword',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
