# Generated by Django 3.0.3 on 2020-02-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_storyentities_storysentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='body_analytics',
        ),
        migrations.RemoveField(
            model_name='story',
            name='title_analytics',
        ),
    ]
