# Generated by Django 3.0.3 on 2020-02-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_modeldetail_scenarioid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='model_label',
            field=models.CharField(default='some_label', max_length=100),
            preserve_default=False,
        ),
    ]
