# Generated by Django 3.0.3 on 2020-02-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0029_auto_20200226_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storybody',
            name='storyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_body', to='apis.Story'),
        ),
        migrations.AlterField(
            model_name='storyentities',
            name='storyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_entities', to='apis.Story'),
        ),
        migrations.AlterField(
            model_name='storysentiment',
            name='storyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_sentiment', to='apis.Story'),
        ),
    ]
