# Generated by Django 3.0.3 on 2020-03-13 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0033_auto_20200302_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashuser',
            name='setupDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
