# Generated by Django 3.0.3 on 2020-03-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0037_story_scenarioid'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entryVerified',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
