# Generated by Django 3.0.3 on 2020-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0052_bucket_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='description',
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('demo', 'Demo'), ('retired', 'Retired')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('demo', 'Demo'), ('retired', 'Retired')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
    ]
