# Generated by Django 3.0.3 on 2020-05-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0055_auto_20200506_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='wikiResource',
            new_name='wikipedia',
        ),
    ]
