# Generated by Django 3.0.3 on 2020-05-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0056_auto_20200506_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='wikipedia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storyentityref',
            name='wikipedia',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
