# Generated by Django 3.0.3 on 2020-05-07 06:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0057_auto_20200506_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
