# Generated by Django 3.0.3 on 2020-05-09 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0059_entity_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='scenarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to='apis.Scenario'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='scenarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='apis.Scenario'),
        ),
        migrations.DeleteModel(
            name='Alias',
        ),
    ]
