# Generated by Django 3.0.3 on 2020-05-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0060_auto_20200509_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyentityref',
            name='alias',
        ),
    ]
