# Generated by Django 3.0.3 on 2020-05-22 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0062_auto_20200513_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
