# Generated by Django 3.0.3 on 2020-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0064_auto_20200522_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashuser',
            name='role',
            field=models.CharField(choices=[('alrt-admin', 'Alrt Admin'), ('alrt-sme', 'Alrt SME'), ('alrt-qa', 'Alrt QA'), ('demo-user', 'Demo User'), ('client-admin', 'Client Admin'), ('client-user', 'Client User')], default='client-user', max_length=25),
            preserve_default=False,
        ),
    ]
