# Generated by Django 3.0.3 on 2020-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0067_scenario_customentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytype',
            name='entry',
            field=models.CharField(choices=[('custom', 'Custom'), ('auto', 'Auto')], default='auto', max_length=10),
            preserve_default=False,
        ),
    ]
