# Generated by Django 3.0.3 on 2020-02-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20200221_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
