# Generated by Django 3.0.3 on 2020-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20200221_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
