# Generated by Django 3.0.3 on 2020-02-22 17:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_auto_20200221_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySentiment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_headline', models.BooleanField()),
                ('sentiment', django.contrib.postgres.fields.jsonb.JSONField()),
                ('storyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryEntities',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_headline', models.BooleanField()),
                ('entities', django.contrib.postgres.fields.jsonb.JSONField()),
                ('storyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Story')),
            ],
        ),
    ]
