# Generated by Django 3.0.3 on 2020-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_remove_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetail',
            name='bucket',
            field=models.CharField(default='production_models', max_length=100),
            preserve_default=False,
        ),
    ]
