# Generated by Django 3.0.3 on 2020-03-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0030_auto_20200227_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='score',
        ),
    ]
