# Generated by Django 3.0.3 on 2020-03-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0032_source_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketscore',
            name='grossScore',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='entityscore',
            name='grossScore',
            field=models.FloatField(),
        ),
    ]
