# Generated by Django 3.0.3 on 2020-03-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0038_entity_entryverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entryVerified',
            field=models.BooleanField(default=False),
        ),
    ]
