# Generated by Django 3.0.3 on 2020-03-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0041_auto_20200329_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='entityType',
        ),
    ]
