# Generated by Django 3.0.3 on 2020-03-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0042_remove_entity_entitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entityType',
            field=models.ForeignKey(default='448499d4-8d6a-4250-b179-768279566439', on_delete=django.db.models.deletion.PROTECT, to='apis.EntityType'),
            preserve_default=False,
        ),
    ]
