# Generated by Django 3.0.3 on 2020-04-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0044_scenario_entitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='mode',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('auto', 'Auto')], default='portfolio', max_length=10),
            preserve_default=False,
        ),
    ]
