# Generated by Django 3.0.3 on 2020-04-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0045_scenario_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyentitymap',
            name='mentions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storyentitymap',
            name='salience',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='storyentityref',
            name='wikipedia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
