# Generated by Django 3.0.3 on 2020-04-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0046_auto_20200406_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyentityref',
            name='alias',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyentityref',
            name='render',
            field=models.BooleanField(default=True),
        ),
    ]
