# Generated by Django 3.0.3 on 2020-04-29 18:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0047_auto_20200420_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('scenarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Scenario')),
            ],
        ),
    ]
