# Generated by Django 3.0.3 on 2020-04-30 16:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0049_auto_20200430_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='name',
        ),
        migrations.AddField(
            model_name='keywords',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], size=None),
        ),
    ]
