# Generated by Django 3.0.3 on 2020-05-01 16:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0053_auto_20200501_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('demo', 'Demo'), ('retired', 'Retired'), ('unverified', 'Unverified')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('demo', 'Demo'), ('retired', 'Retired'), ('unverified', 'Unverified')], max_length=10),
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('scenarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Scenario')),
            ],
        ),
    ]
