# Generated by Django 3.0.3 on 2020-05-07 12:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0059_entity_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ml_cluster',
            },
        ),
        migrations.CreateModel(
            name='ClusterMap',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clusterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Cluster')),
                ('storyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Story')),
            ],
            options={
                'db_table': 'ml_clustermap',
            },
        ),
    ]
