# Generated by Django 3.0.3 on 2020-05-25 12:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_clustermap_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryWarehouse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_id', models.UUIDField()),
                ('story_title', models.CharField(max_length=2000)),
                ('story_url', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField()),
                ('domain', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=100)),
                ('source_country', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=200)),
                ('entity_id', models.UUIDField()),
                ('scenario_id', models.UUIDField()),
                ('story_body', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField()),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField()),
                ('entities', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hotness', django.contrib.postgres.fields.jsonb.JSONField()),
                ('bucket_score', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sentiment', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
