# Generated by Django 3.0.3 on 2020-05-30 05:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_storywarehouse_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoWarehouse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storyID', models.UUIDField()),
                ('title', models.CharField(max_length=2000)),
                ('url', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField()),
                ('domain', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=100)),
                ('source_country', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=200)),
                ('entityID', models.UUIDField()),
                ('scenarioID', models.UUIDField()),
                ('story_body', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField()),
                ('cluster', models.IntegerField()),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField()),
                ('entities', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hotness', django.contrib.postgres.fields.jsonb.JSONField()),
                ('bucket_scores', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sentiment', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioWarehouse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storyID', models.UUIDField()),
                ('title', models.CharField(max_length=2000)),
                ('url', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField()),
                ('domain', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=100)),
                ('source_country', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=200)),
                ('entityID', models.UUIDField()),
                ('scenarioID', models.UUIDField()),
                ('story_body', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField()),
                ('cluster', models.IntegerField()),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField()),
                ('entities', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hotness', django.contrib.postgres.fields.jsonb.JSONField()),
                ('bucket_scores', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sentiment', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='StoryWarehouse',
        ),
    ]
