# Generated by Django 3.0.3 on 2020-05-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200530_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='autowarehouse',
            name='search_keyword',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliowarehouse',
            name='search_keyword',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
